# Generated by Django 5.0.7 on 2024-08-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydocument',
            old_name='document_file',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='deliverydocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='deliveryschedule',
            name='status',
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
