# Generated by Django 5.0.7 on 2024-08-01 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_booking_status'),
        ('delivery', '0002_rename_document_file_deliverydocument_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
