# Generated by Django 5.0.7 on 2024-07-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_emailaddress_unique_primary_email'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('otp_static', '0003_add_timestamps'),
        ('otp_totp', '0003_add_timestamps'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
        ('users', '0003_customuser_otp_delete_otpcode_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
