# Generated by Django 5.0.7 on 2024-07-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='code',
            new_name='otp',
        ),
    ]
