# Generated by Django 5.0.7 on 2024-11-24 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
