# Generated by Django 5.0.7 on 2025-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notification_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking-payment-verified', 'Booking Payment Verified'), ('subscription-payment-verified', 'Subscription Payment Verified'), ('booking-created', 'Booking Created'), ('booking-cost-added', 'Booking Cost Added'), ('truck-uploaded', 'Truck Uploaded'), ('truck-available', 'Truck Available'), ('truck-booked', 'Truck Booked'), ('delivery-completed', 'Delivery Completed')], default='booking-created', max_length=50),
        ),
    ]
