# Generated by Django 5.0.7 on 2024-07-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
