# Generated by Django 5.0.7 on 2024-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=11),
        ),
    ]
