# Generated by Django 5.0.7 on 2024-12-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='image',
        ),
        migrations.CreateModel(
            name='TruckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trucks/')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.truck')),
            ],
        ),
    ]
