# Generated by Django 5.0.7 on 2024-12-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_truck_image_truckimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
